name: Build and Deploy Chrome Extension

on: 
  push:  
    branches:
      - main
  workflow_dispatch:      #Allows manual trigger in GitHub Actions. Must be triggered manually

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create zip for Chrome Web Store
        run: | 
          mkdir dist
          zip -r dist/extension.zip . -x '*.git*' 'node_modules/*' '.github/*'

      - name: Upload to Chrome Web Store
        uses: Klemensas/chrome-extension-upload-action@v1.3
        with:
          refresh-token: ${{ secrets.REFRESH_TOKEN }} 
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          app-id: ${{ secrets.EXTENSION_ID }}
          file-name: dist/extension.zip

      - name: Publish to Chrome Web Store
        run: |
          curl -X POST \
          -H "Authorization: Bearer $(curl -s -X POST -d client_id=${{ secrets.CLIENT_ID }} -d client_secret=${{ secrets.CLIENT_SECRET }} -d refresh_token=${{ secrets.REFRESH_TOKEN }} -d grant_type=refresh_token https://accounts.google.com/o/oauth2/token | jq -r '.access_token')" \
          -H "x-goog-api-version: 2" \
          -H "Content-Length: 0" \
          "https://www.googleapis.com/chromewebstore/v1.1/items/${{ secrets.EXTENSION_ID }}/publish"

          
      
